modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Configurable%20Mob%20Potion%20Effects"
logoFile="icon.png"

[[mods]]
modId="configurablemobpotioneffects"
version="3.5"
displayName="Configurable Mob Potion Effects"
displayURL="https://serilum.com/mod/configurable-mob-potion-effects"
authors="Rick South"
description='''Configurably set potion effects for all living entities, permanent for self and on damage for others.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.configurablemobpotioneffects]]
    modId="collective"
    mandatory=true
    versionRange="[7.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configurablemobpotioneffects]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"
