modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Configurable%20Mob%20Potion%20Effects"
logoFile="icon.png"

[[mods]]
modId="configurablemobpotioneffects"
version="3.4"
displayName="Configurable Mob Potion Effects"
displayURL="https://serilum.com/mod/configurable-mob-potion-effects"
authors="Rick South"
description='''Configurably set potion effects for all living entities, permanent for self and on damage for others.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.configurablemobpotioneffects]]
    modId="collective"
    type="required"
    versionRange="[7.64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configurablemobpotioneffects]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[dependencies.configurablemobpotioneffects]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.31,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "configurablemobpotioneffects.mixins.json"